name: Build and Deploy
permissions:
  contents: write
on:
  push:
    branches:
      - master # change to your desired branch name
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: actions/checkout@v3
      #- run: yarn install --frozen-lockfile # run install script
      #- run: yarn build # run build script
      # npm version:
      - run: npm ci
      - run: npm run build
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          BRANCH: gh-pages
          FOLDER: dist # your output folder name